language: cpp
sudo: required
dist: trusty
compiler: clang

addons: &addons
  apt:
    sources: &sources
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
    packages: &packages
      # install toolchains
      - g++-4.9
      - g++-5
      - clang-format-3.7
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - python-pip
      - libmicrohttpd-dev
      - libmicrohttpd10
      - libssl-dev

install:
  # Download conan
  - wget http://downloads.conan.io/latest_debian -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb

  # Automatic detection of your arch, compiler, etc
  - conan install --options build_luna_tests=True --options build_luna_coverage=True --build=missing

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            *sources
          packages:
            *packages
      env: COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            *sources
          packages:
      env: COMPILER=g++-5 CCOMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            *sources
          packages:
            *packages
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            *sources
          packages:
            *packages
      env: COMPILER=clang++-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            *sources
          packages:
            *packages
      env: COMPILER=clang++-3.8

script:
  - conan build
  - ./bin/luna_tests

#after_success:
#  - if [ "$GENERATE_COVERAGE" == "ON" ]; then coveralls -i 'luna' -i 'include' -e '../include/luna.h' --root '../' --verbose --gcov-options '\-lp' --gcov 'gcov-4.9'; fi

#after_script:
#  - if [ "$FORMAT_CHECK" == "ON" ]; then cd .. && ./format-check.sh; fi
