#
#       _
#   ___/__)
#  (, /      __   _
#    /   (_(_/ (_(_(_
#   (________________
#                    )
#
#  Luna
#  a web framework in modern C++
#
#  Copyright © 2016–2017 D.E. Goodman-Wilson
#

coverage:
  ignore:
    - examples/*
    - tests/*